### ISSUE TITLE
Cannot type space or enter keys in Documenter editor on Linux 64 bit using 32 bit vm for Pharo

### ISSUE THREAD

**Issue by souravdatta** [feenkcom/gtoolkit-documenter#1]
## OS

Linux Ubuntu 18.10 LTS 64 bit

## Pharo

Pharo 6.1 32 bit. Running with 32 bit libraries installed for linux.

## To reproduce

`GtDocumenter editorForText: 'Ok'`

## What happens

The editor opens in alright but typing 'enter' and 'space' (or any other special characters) does not produce the correct value in the editor. Refer to screenshot.

Also, pressing backspace produces a lot exceptions.

## How gtoolkit was installed

By running:

`Metacello new
   baseline: 'GToolkit';
   repository: 'github://feenkcom/gtoolkit/src';
   load.
`

Note: I am very new to Pharo eco system, so please let me know if I am missing something before installing Gtoolkit.
![pharo_documenter_1](https://user-images.githubusercontent.com/1576318/41467349-ce8cfdec-70c3-11e8-8eeb-3e19ad8b69aa.png)

**Comment by girba** [comment]
Currently, we support rendering in 64bit. Can you try reinstalling GToolkit in a Pharo 64 bit image and see if it works?

**Comment by souravdatta** [comment]
I will give it a shot. Currently with Pharo Launcher I am unable to launch a 64 bit image for some reason, it quits abruptly after launching. But I will test with a fresh downloaded image and reply.

**Comment by souravdatta** [comment]
I have tested with 64 bit and I no longer get the white space issue reported above. However, I get another problem when trying to edit anything. For example, when I inspect the following `GtDocumenter editorForText: BrToggleExamples comment.` in a playground I get text should be valid Pillar format error, and this happens for a lot of texts. Loading a `valid` Pillar file from disk/code works fine.
![pharogtoolkit_2](https://user-images.githubusercontent.com/1576318/41860847-4b2662d4-78bd-11e8-9e8e-b42e2053d1cc.png)

**Comment by girba** [comment]
Great. Indeed, this was a bug we had for a few hours and I think you got unlucky :). Please install the whole thing again. It should work fine now.

Just make sure that when you do load the code, the iceberg local cache is empty (or manually, update the repositories on disk)

**Comment by souravdatta** [comment]
Great! I tried with a new install and things seems to be working again. 
However, I still get a lot of exceptions (mainly index error) thrown when I type Backspace key. But I guess that's a different issue from the one for which I created this thread. So this one can be closed, thanks!

**Comment by JurajKubelka** [comment]
Hi @souravdatta! Thank you for your effort and do not hesitate to share your issues and positive experience with us :-) I suppose that the index error is the one we know about. On other hand, it is always better to report it.
